use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ToolFamily {
    Filesystem,
    Web,
    Exec,
    Planning,
    Offload,
    Memory,
    Mcp,
    Agent,
    Browser,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ToolName {
    FsRead,
    FsWrite,
    FsPatch,
    FsReadText,
    FsReadLines,
    FsSearchText,
    FsFindInFiles,
    FsWriteText,
    FsPatchText,
    FsReplaceLines,
    FsInsertText,
    FsMkdir,
    FsMove,
    FsTrash,
    FsList,
    FsGlob,
    FsSearch,
    WebFetch,
    WebSearch,
    BrowserOpen,
    BrowserSnapshot,
    BrowserText,
    BrowserClick,
    BrowserFill,
    BrowserPress,
    BrowserWait,
    BrowserScroll,
    BrowserEval,
    BrowserScreenshot,
    BrowserPdf,
    BrowserStatus,
    BrowserClose,
    ExecStart,
    ExecReadOutput,
    ExecWait,
    ExecKill,
    PlanRead,
    PlanWrite,
    InitPlan,
    AddTask,
    SetTaskStatus,
    AddTaskNote,
    EditTask,
    PlanSnapshot,
    PlanLint,
    PromptBudgetRead,
    PromptBudgetUpdate,
    AutonomyStateRead,
    SkillList,
    SkillRead,
    SkillEnable,
    SkillDisable,
    SkillInstall,
    ArtifactRead,
    ArtifactSearch,
    ArtifactPin,
    ArtifactUnpin,
    DeliverFile,
    MemoryAdd,
    MemorySearch,
    MemoryList,
    MemoryUpdate,
    MemoryDelete,
    KvGet,
    KvPut,
    KvList,
    KvDelete,
    KnowledgeSearch,
    KnowledgeRead,
    SessionSearch,
    SessionRead,
    SessionWait,
    McpCall,
    McpSearchResources,
    McpReadResource,
    McpSearchPrompts,
    McpGetPrompt,
    AgentList,
    AgentRead,
    AgentCreate,
    ContinueLater,
    ScheduleList,
    ScheduleRead,
    ScheduleCreate,
    ScheduleUpdate,
    ScheduleDelete,
    MessageAgent,
    GrantAgentChainContinuation,
}

impl ToolFamily {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Filesystem => "fs",
            Self::Web => "web",
            Self::Exec => "exec",
            Self::Planning => "plan",
            Self::Offload => "offload",
            Self::Memory => "memory",
            Self::Mcp => "mcp",
            Self::Agent => "agent",
            Self::Browser => "browser",
        }
    }
}

impl ToolName {
    pub fn is_semantic_memory_tool(self) -> bool {
        matches!(
            self,
            Self::MemoryAdd
                | Self::MemorySearch
                | Self::MemoryList
                | Self::MemoryUpdate
                | Self::MemoryDelete
        )
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::FsRead => "fs_read",
            Self::FsWrite => "fs_write",
            Self::FsPatch => "fs_patch",
            Self::FsReadText => "fs_read_text",
            Self::FsReadLines => "fs_read_lines",
            Self::FsSearchText => "fs_search_text",
            Self::FsFindInFiles => "fs_find_in_files",
            Self::FsWriteText => "fs_write_text",
            Self::FsPatchText => "fs_patch_text",
            Self::FsReplaceLines => "fs_replace_lines",
            Self::FsInsertText => "fs_insert_text",
            Self::FsMkdir => "fs_mkdir",
            Self::FsMove => "fs_move",
            Self::FsTrash => "fs_trash",
            Self::FsList => "fs_list",
            Self::FsGlob => "fs_glob",
            Self::FsSearch => "fs_search",
            Self::WebFetch => "web_fetch",
            Self::WebSearch => "web_search",
            Self::BrowserOpen => "browser_open",
            Self::BrowserSnapshot => "browser_snapshot",
            Self::BrowserText => "browser_text",
            Self::BrowserClick => "browser_click",
            Self::BrowserFill => "browser_fill",
            Self::BrowserPress => "browser_press",
            Self::BrowserWait => "browser_wait",
            Self::BrowserScroll => "browser_scroll",
            Self::BrowserEval => "browser_eval",
            Self::BrowserScreenshot => "browser_screenshot",
            Self::BrowserPdf => "browser_pdf",
            Self::BrowserStatus => "browser_status",
            Self::BrowserClose => "browser_close",
            Self::ExecStart => "exec_start",
            Self::ExecReadOutput => "exec_read_output",
            Self::ExecWait => "exec_wait",
            Self::ExecKill => "exec_kill",
            Self::PlanRead => "plan_read",
            Self::PlanWrite => "plan_write",
            Self::InitPlan => "init_plan",
            Self::AddTask => "add_task",
            Self::SetTaskStatus => "set_task_status",
            Self::AddTaskNote => "add_task_note",
            Self::EditTask => "edit_task",
            Self::PlanSnapshot => "plan_snapshot",
            Self::PlanLint => "plan_lint",
            Self::PromptBudgetRead => "prompt_budget_read",
            Self::PromptBudgetUpdate => "prompt_budget_update",
            Self::AutonomyStateRead => "autonomy_state_read",
            Self::SkillList => "skill_list",
            Self::SkillRead => "skill_read",
            Self::SkillEnable => "skill_enable",
            Self::SkillDisable => "skill_disable",
            Self::SkillInstall => "skill_install",
            Self::ArtifactRead => "artifact_read",
            Self::ArtifactSearch => "artifact_search",
            Self::ArtifactPin => "artifact_pin",
            Self::ArtifactUnpin => "artifact_unpin",
            Self::DeliverFile => "deliver_file",
            Self::MemoryAdd => "memory_add",
            Self::MemorySearch => "memory_search",
            Self::MemoryList => "memory_list",
            Self::MemoryUpdate => "memory_update",
            Self::MemoryDelete => "memory_delete",
            Self::KvGet => "kv_get",
            Self::KvPut => "kv_put",
            Self::KvList => "kv_list",
            Self::KvDelete => "kv_delete",
            Self::KnowledgeSearch => "knowledge_search",
            Self::KnowledgeRead => "knowledge_read",
            Self::SessionSearch => "session_search",
            Self::SessionRead => "session_read",
            Self::SessionWait => "session_wait",
            Self::McpCall => "mcp_call",
            Self::McpSearchResources => "mcp_search_resources",
            Self::McpReadResource => "mcp_read_resource",
            Self::McpSearchPrompts => "mcp_search_prompts",
            Self::McpGetPrompt => "mcp_get_prompt",
            Self::AgentList => "agent_list",
            Self::AgentRead => "agent_read",
            Self::AgentCreate => "agent_create",
            Self::ContinueLater => "continue_later",
            Self::ScheduleList => "schedule_list",
            Self::ScheduleRead => "schedule_read",
            Self::ScheduleCreate => "schedule_create",
            Self::ScheduleUpdate => "schedule_update",
            Self::ScheduleDelete => "schedule_delete",
            Self::MessageAgent => "message_agent",
            Self::GrantAgentChainContinuation => "grant_agent_chain_continuation",
        }
    }
}
