use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ToolFamily {
    Filesystem,
    Web,
    Exec,
    Planning,
    Offload,
    Memory,
    Mcp,
    Agent,
    Browser,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ToolName {
    FsRead,
    FsWrite,
    FsPatch,
    FsReadText,
    FsReadLines,
    FsSearchText,
    FsFindInFiles,
    FsWriteText,
    FsPatchText,
    FsReplaceLines,
    FsInsertText,
    FsMkdir,
    FsMove,
    FsTrash,
    FsList,
    FsGlob,
    FsSearch,
    WebFetch,
    WebSearch,
    BrowserOpen,
    BrowserSnapshot,
    BrowserText,
    BrowserClick,
    BrowserFill,
    BrowserPress,
    BrowserWait,
    BrowserScroll,
    BrowserEval,
    BrowserScreenshot,
    BrowserPdf,
    BrowserStatus,
    BrowserClose,
    ExecStart,
    ExecReadOutput,
    ExecWait,
    ExecKill,
    PlanRead,
    PlanWrite,
    InitPlan,
    AddTask,
    SetTaskStatus,
    AddTaskNote,
    EditTask,
    PlanSnapshot,
    PlanLint,
    PromptBudgetRead,
    PromptBudgetUpdate,
    AutonomyStateRead,
    SkillList,
    SkillRead,
    SkillEnable,
    SkillDisable,
    SkillInstall,
    ArtifactRead,
    ArtifactSearch,
    ArtifactPin,
    ArtifactUnpin,
    DeliverFile,
    MemoryAdd,
    MemorySearch,
    MemoryList,
    MemoryUpdate,
    MemoryDelete,
    KvGet,
    KvPut,
    KvList,
    KvDelete,
    KnowledgeSearch,
    KnowledgeRead,
    SessionSearch,
    SessionRead,
    SessionWait,
    McpCall,
    McpSearchResources,
    McpReadResource,
    McpSearchPrompts,
    McpGetPrompt,
    AgentList,
    AgentRead,
    AgentCreate,
    ContinueLater,
    ScheduleList,
    ScheduleRead,
    ScheduleCreate,
    ScheduleUpdate,
    ScheduleDelete,
    MessageAgent,
    GrantAgentChainContinuation,
}

impl ToolFamily {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Filesystem => "fs",
            Self::Web => "web",
            Self::Exec => "exec",
            Self::Planning => "plan",
            Self::Offload => "offload",
            Self::Memory => "memory",
            Self::Mcp => "mcp",
            Self::Agent => "agent",
            Self::Browser => "browser",
        }
    }
}

impl ToolName {
    pub fn from_openai_function_name(name: &str) -> Option<Self> {
        Some(match name {
            "fs_read" => Self::FsRead,
            "fs_write" => Self::FsWrite,
            "fs_patch" => Self::FsPatch,
            "fs_read_text" => Self::FsReadText,
            "fs_read_lines" => Self::FsReadLines,
            "fs_search_text" => Self::FsSearchText,
            "fs_find_in_files" => Self::FsFindInFiles,
            "fs_write_text" => Self::FsWriteText,
            "fs_patch_text" => Self::FsPatchText,
            "fs_replace_lines" => Self::FsReplaceLines,
            "fs_insert_text" => Self::FsInsertText,
            "fs_mkdir" => Self::FsMkdir,
            "fs_move" => Self::FsMove,
            "fs_trash" => Self::FsTrash,
            "fs_list" => Self::FsList,
            "fs_glob" => Self::FsGlob,
            "fs_search" => Self::FsSearch,
            "web_fetch" => Self::WebFetch,
            "web_search" => Self::WebSearch,
            "browser_open" => Self::BrowserOpen,
            "browser_snapshot" => Self::BrowserSnapshot,
            "browser_text" => Self::BrowserText,
            "browser_click" => Self::BrowserClick,
            "browser_fill" => Self::BrowserFill,
            "browser_press" => Self::BrowserPress,
            "browser_wait" => Self::BrowserWait,
            "browser_scroll" => Self::BrowserScroll,
            "browser_eval" => Self::BrowserEval,
            "browser_screenshot" => Self::BrowserScreenshot,
            "browser_pdf" => Self::BrowserPdf,
            "browser_status" => Self::BrowserStatus,
            "browser_close" => Self::BrowserClose,
            "exec_start" => Self::ExecStart,
            "exec_read_output" => Self::ExecReadOutput,
            "exec_wait" => Self::ExecWait,
            "exec_kill" => Self::ExecKill,
            "plan_read" => Self::PlanRead,
            "plan_write" => Self::PlanWrite,
            "init_plan" => Self::InitPlan,
            "add_task" => Self::AddTask,
            "set_task_status" => Self::SetTaskStatus,
            "add_task_note" => Self::AddTaskNote,
            "edit_task" => Self::EditTask,
            "plan_snapshot" => Self::PlanSnapshot,
            "plan_lint" => Self::PlanLint,
            "prompt_budget_read" => Self::PromptBudgetRead,
            "prompt_budget_update" => Self::PromptBudgetUpdate,
            "autonomy_state_read" => Self::AutonomyStateRead,
            "skill_list" => Self::SkillList,
            "skill_read" => Self::SkillRead,
            "skill_enable" => Self::SkillEnable,
            "skill_disable" => Self::SkillDisable,
            "skill_install" => Self::SkillInstall,
            "artifact_read" => Self::ArtifactRead,
            "artifact_search" => Self::ArtifactSearch,
            "artifact_pin" => Self::ArtifactPin,
            "artifact_unpin" => Self::ArtifactUnpin,
            "deliver_file" => Self::DeliverFile,
            "memory_add" => Self::MemoryAdd,
            "memory_search" => Self::MemorySearch,
            "memory_list" => Self::MemoryList,
            "memory_update" => Self::MemoryUpdate,
            "memory_delete" => Self::MemoryDelete,
            "kv_get" => Self::KvGet,
            "kv_put" => Self::KvPut,
            "kv_list" => Self::KvList,
            "kv_delete" => Self::KvDelete,
            "knowledge_search" => Self::KnowledgeSearch,
            "knowledge_read" => Self::KnowledgeRead,
            "session_search" => Self::SessionSearch,
            "session_read" => Self::SessionRead,
            "session_wait" => Self::SessionWait,
            "mcp_call" => Self::McpCall,
            "mcp_search_resources" => Self::McpSearchResources,
            "mcp_read_resource" => Self::McpReadResource,
            "mcp_search_prompts" => Self::McpSearchPrompts,
            "mcp_get_prompt" => Self::McpGetPrompt,
            "agent_list" => Self::AgentList,
            "agent_read" => Self::AgentRead,
            "agent_create" => Self::AgentCreate,
            "continue_later" => Self::ContinueLater,
            "schedule_list" => Self::ScheduleList,
            "schedule_read" => Self::ScheduleRead,
            "schedule_create" => Self::ScheduleCreate,
            "schedule_update" => Self::ScheduleUpdate,
            "schedule_delete" => Self::ScheduleDelete,
            "message_agent" => Self::MessageAgent,
            "grant_agent_chain_continuation" => Self::GrantAgentChainContinuation,
            _ => return None,
        })
    }

    pub fn is_semantic_memory_tool(self) -> bool {
        matches!(
            self,
            Self::MemoryAdd
                | Self::MemorySearch
                | Self::MemoryList
                | Self::MemoryUpdate
                | Self::MemoryDelete
        )
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::FsRead => "fs_read",
            Self::FsWrite => "fs_write",
            Self::FsPatch => "fs_patch",
            Self::FsReadText => "fs_read_text",
            Self::FsReadLines => "fs_read_lines",
            Self::FsSearchText => "fs_search_text",
            Self::FsFindInFiles => "fs_find_in_files",
            Self::FsWriteText => "fs_write_text",
            Self::FsPatchText => "fs_patch_text",
            Self::FsReplaceLines => "fs_replace_lines",
            Self::FsInsertText => "fs_insert_text",
            Self::FsMkdir => "fs_mkdir",
            Self::FsMove => "fs_move",
            Self::FsTrash => "fs_trash",
            Self::FsList => "fs_list",
            Self::FsGlob => "fs_glob",
            Self::FsSearch => "fs_search",
            Self::WebFetch => "web_fetch",
            Self::WebSearch => "web_search",
            Self::BrowserOpen => "browser_open",
            Self::BrowserSnapshot => "browser_snapshot",
            Self::BrowserText => "browser_text",
            Self::BrowserClick => "browser_click",
            Self::BrowserFill => "browser_fill",
            Self::BrowserPress => "browser_press",
            Self::BrowserWait => "browser_wait",
            Self::BrowserScroll => "browser_scroll",
            Self::BrowserEval => "browser_eval",
            Self::BrowserScreenshot => "browser_screenshot",
            Self::BrowserPdf => "browser_pdf",
            Self::BrowserStatus => "browser_status",
            Self::BrowserClose => "browser_close",
            Self::ExecStart => "exec_start",
            Self::ExecReadOutput => "exec_read_output",
            Self::ExecWait => "exec_wait",
            Self::ExecKill => "exec_kill",
            Self::PlanRead => "plan_read",
            Self::PlanWrite => "plan_write",
            Self::InitPlan => "init_plan",
            Self::AddTask => "add_task",
            Self::SetTaskStatus => "set_task_status",
            Self::AddTaskNote => "add_task_note",
            Self::EditTask => "edit_task",
            Self::PlanSnapshot => "plan_snapshot",
            Self::PlanLint => "plan_lint",
            Self::PromptBudgetRead => "prompt_budget_read",
            Self::PromptBudgetUpdate => "prompt_budget_update",
            Self::AutonomyStateRead => "autonomy_state_read",
            Self::SkillList => "skill_list",
            Self::SkillRead => "skill_read",
            Self::SkillEnable => "skill_enable",
            Self::SkillDisable => "skill_disable",
            Self::SkillInstall => "skill_install",
            Self::ArtifactRead => "artifact_read",
            Self::ArtifactSearch => "artifact_search",
            Self::ArtifactPin => "artifact_pin",
            Self::ArtifactUnpin => "artifact_unpin",
            Self::DeliverFile => "deliver_file",
            Self::MemoryAdd => "memory_add",
            Self::MemorySearch => "memory_search",
            Self::MemoryList => "memory_list",
            Self::MemoryUpdate => "memory_update",
            Self::MemoryDelete => "memory_delete",
            Self::KvGet => "kv_get",
            Self::KvPut => "kv_put",
            Self::KvList => "kv_list",
            Self::KvDelete => "kv_delete",
            Self::KnowledgeSearch => "knowledge_search",
            Self::KnowledgeRead => "knowledge_read",
            Self::SessionSearch => "session_search",
            Self::SessionRead => "session_read",
            Self::SessionWait => "session_wait",
            Self::McpCall => "mcp_call",
            Self::McpSearchResources => "mcp_search_resources",
            Self::McpReadResource => "mcp_read_resource",
            Self::McpSearchPrompts => "mcp_search_prompts",
            Self::McpGetPrompt => "mcp_get_prompt",
            Self::AgentList => "agent_list",
            Self::AgentRead => "agent_read",
            Self::AgentCreate => "agent_create",
            Self::ContinueLater => "continue_later",
            Self::ScheduleList => "schedule_list",
            Self::ScheduleRead => "schedule_read",
            Self::ScheduleCreate => "schedule_create",
            Self::ScheduleUpdate => "schedule_update",
            Self::ScheduleDelete => "schedule_delete",
            Self::MessageAgent => "message_agent",
            Self::GrantAgentChainContinuation => "grant_agent_chain_continuation",
        }
    }
}
